version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=DevDB
      - DB_USER=DevUser
      - DB_PASSWORD=change_me_123
    depends_on:
      - db
      
  db:
    image: postgres
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=DevDB
      - POSTGRES_USER=DevUser
      - POSTGRES_PASSWORD=change_me_123

volumes:
  dev-db-data:

